### ISSUE TITLE
Certificate untrusted problem ?

### ISSUE THREAD

**Issue by source83** [vrsites/vrsites-public-issues#13]
Looks like there might be some problems with the cert for vrsites atm.

www.vrsites.com uses an invalid security certificate. The certificate is only valid for the following names: *.prod.phx3.secureserver.net, prod.phx3.secureserver.net (Error code: ssl_error_bad_cert_domain)

**Comment by sirkitree** [comment]
You can't actually log into www.vrsites.com so we don't have a sec for it. We have one for https://beta.vrsites.com/

**Comment by source83** [comment]
Okay, but that causes problems for the rooms in the vrsites reddit, all of them use the www.vrsites prefix

**Comment by sirkitree** [comment]
Oh, which rooms, the old archives?

**Comment by JordekFluffball** [comment]
This might be the cause of VRSites rooms that use HTTPS not working on Mac/Linux.

**Comment by soukron** [comment]
See https://www.reddit.com/r/janusVR/comments/3yarps/accessing_to_https_vrsites_not_working/.

I fixed adding to my trusted CAs a bundle published by COMODO. Not sure how you can fixed from your side in other way than getting a better signed certificate.

**Comment by source83** [comment]
you can use letsencrypt, I'm using them on my server now.
https://letsencrypt.org/

**Comment by sirkitree** [comment]
This works in in all of my browsers, but I'm able to reproduce through Janus on OSX. I get the default room instead of the url I'm trying for, but there is no indication of an error.

Are we sure this isn't a change needed in Janus since it seems to work elsewhere?

**Comment by soukron** [comment]
@sirkitree it's in no one's land but both of you can fix it: Janus relies on java/operating system vaults  to validate vrsites' certificate. Regular browsers have enough CA root certificates in their vault to be able to validate vrsites certificate (before relying to operating system certificates), and that's why works in your browsers. 

In the other hand, JanusVR relies on JavaVM certificates stores (which seems to be unable to validate vrsites certificate) and in case of missing root CA, then relies it to operating system vault. 
In my link I pointed how to add a root CA to Linux to validate your sites.

Ways to fix this:
 - get a better certificate. this usually becomes in paying more to COMODO to get a certificate signed by a better known CA which will be included in Java store. 
 - @source83 seems to be using let's encrypt certificates and according to him it works fine. In Reddit thread I also confirmed that JanusVR works fine with sites with certificates signed by them. Maybe you can evalutate to change your ssl certificate with a Let's encrypt one.
 - talk to JanusVR to check if they can include COMODO root CA which signed your certificate so it won't fail.

Not sure if this helps.

**Comment by sirkitree** [comment]
It does help @soukron, thanks! I'll see if James can add it, but I'm also looking into letsencrypt as it seems like a much easier way to actually manage certs in general. I'm a bit surprised that letsencrypt would be supported more than COMODO which is a fairly widely used provider.

**Comment by soukron** [comment]
I've been digging a bit more.
According to COMODO [1] and Oracle [2], COMODO SHA2 root certificates were included in Java 8u51 released on July 2015, so any Java JRE previous to 8u51 will suffer this problem. 

Just add a warning note in somewhere regarding the min required version and you'll be fine.

[1] https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/296/17/
[2] http://www.oracle.com/technetwork/java/javase/8u51-relnotes-2587590.html

**Comment by sirkitree** [comment]
switched to letsencrypt and it seems to be working in janus now. thanks all!
