### ISSUE TITLE
renaming any javascripts (.js) to .js.txt

### ISSUE THREAD

**Issue by asurazero** [vrsites/vrsites-public-issues#7]
when i try to upload javascripts it changes my files to  .js.txt   citing security concerns.

**Comment by sirkitree** [comment]
Is this for the vrsites.com or the beta?

**Comment by asurazero** [comment]
vrsites beta

**Comment by sirkitree** [comment]
Backdrop (our content management system) does this by default as a security measure.

Janus should read the file just fine though.

We could set `allow_insecure_uploads` as described in [`file_munge_filename()`](https://api.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_munge_filename/1) and instead edit the server configuration to ensure that files are not executed by the server.

But I'm not totally sure I understand the security implications just yet. Will look into this.

**Comment by bnolan** [comment]
AFAIK it's not a big security hole, any js files hosted on your site will be run in the security model of the site that includes those files. Hosting straight html is a bigger hole tbh. Are you serving all the .html files off a seperate domain that doesn't have access to the cookies that people use to authenticate with backdrop?

**Comment by sirkitree** [comment]
Ok. I think I'm ok with this change and I'll make the necessary adjustments soon.

As for the html, that's a different issue, but we don't allow upload of .html files. The markup is actually in the database (I know, I know, not great either) but it allows us to validate the markup against a set of allowed tags rather than just allowing full html.
